### PR TITLE
Adds a first resolving authorizer implementation.

### PR DESCRIPTION
**Pull request by filmil**
Note first, the approach here is wrong: we won't be reading
PolicyNodeSpecs from the API server.  That said, it seems interesting to
check out what happens when we do, so I left this in.

Changes here are:
- Factor the authorizer out of the main package.
Only server remains.

- Started resolving policy rules.

- Fix the authorizer main_test.go to pass.  Note that the current setup
*may* mean that the webhook authorizer will start denying things up
until we actually add some configuration.  But since our dev deployments
run alongside an AlwaysAllow, it may be OK.

- Added a working, but weird authorizer test.

---
This change is [Reviewable](https://reviewable.io/reviews/mdruskin/kubernetes-enterprise-control/28)

### CODE REVIEW

**Comment by briantkennedy** [comment]
The main.go is getting pretty big, don't need to do this now, but you may want to consider moving some of the code out into a separate package soon.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/authorizer/main.go, line 122 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-KuWrDFfVoZI-wwCdpVR:-KuWrDFfVoZI-wwCdpVS:bywhozd) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/725e6e7d41fa4656dd693e074802054d76402b81/cmd/authorizer/main.go#L122)):*
> ```Go
> 			glog.Errorf(
> 				"Could not unmarshal as request spec: %v",
> 				body)
> ```

Do you need to return an error to the client here?  From the docs I can't quite tell if it will auto-respond with anything in particular here.

---

*[cmd/authorizer/main.go, line 141 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-KuWr9qRIb2F5SBEfPzB:-KuWr9qSyGPq6JvtQqvS:b-z46h7w) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/725e6e7d41fa4656dd693e074802054d76402b81/cmd/authorizer/main.go#L141)):*
> ```Go
> 		if err != nil {
> 			glog.Errorf("While marshalling response: %v", err)
> 			return
> ```

Same question as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-:-KuWqKUl6T3PPlkDGnpx:b-6e1aly)*

**Comment by filmil** [comment]
Agreed. I wasn't in a hurry as it seems that it would be easy to detach the logic to a pkg/ somewhere.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/authorizer/main.go, line 122 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-KuWrDFfVoZI-wwCdpVR:-KuWsOlF3ukFeFSjZeG9:b4lspcw) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/725e6e7d41fa4656dd693e074802054d76402b81/cmd/authorizer/main.go#L122)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

Do you need to return an error to the client here?  From the docs I can't quite tell if it will auto-respond with anything in particular here.
</blockquote></details>

I should probably return an error like in the content type check above.

---

*[cmd/authorizer/main.go, line 141 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-KuWr9qRIb2F5SBEfPzB:-KuWsVBOQPd0IWgbr8L9:be81aw9) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/725e6e7d41fa4656dd693e074802054d76402b81/cmd/authorizer/main.go#L141)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

Same question as above
</blockquote></details>

Let me do that now, then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-:-KuWsBAvqrrewTkq381H:b-v2ux3r)*

**Comment by briantkennedy** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-:-KuX-IJzk9ctL1Uuzn_d:bnfp4nl)*

**Comment by filmil** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/authorizer/main.go, line 122 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-KuWrDFfVoZI-wwCdpVR:-KuX0YWUokSXyU41cK1V:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/725e6e7d41fa4656dd693e074802054d76402b81/cmd/authorizer/main.go#L122)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

I should probably return an error like in the content type check above.
</blockquote></details>

Done.

---

*[cmd/authorizer/main.go, line 141 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28#-KuWr9qRIb2F5SBEfPzB:-KuX0XkWX9KS5R1SGrGi:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/725e6e7d41fa4656dd693e074802054d76402b81/cmd/authorizer/main.go#L141)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Let me do that now, then.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/28)*

**Pull request merged**
