### PR TITLE
Fixes the way the static docker binary is built.

### PR DESCRIPTION
**Pull request by filmil**
In the old code the call to the 'test' target would trample over the authorizer_no_cgo target.

---
This change is [Reviewable](https://reviewable.io/reviews/mdruskin/kubernetes-enterprise-control/35)

### CODE REVIEW

**Comment by briantkennedy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/authorizer/Makefile, line 51 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35#-Kuvk8fFe-T4-dyAYTAT:-Kuvk8fGP4oVrYeHO-gx:bpg3fjc) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/d889572318826df14a966d4687531395975147c7/cmd/authorizer/Makefile#L51)):*
> ```Makefile
> 
> # Build a docker container for the minikube docker repository.
> docker_minikube: test authorizer_no_cgo server.key server.crt
> ```

maybe have authorizer_no_cgo depend on test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35)*

**Comment by briantkennedy** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35#-:-KuvkMGKcgnLRVaJKaIS:bnfp4nl)*

**Comment by filmil** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/authorizer/Makefile, line 51 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35#-Kuvk8fFe-T4-dyAYTAT:-KuvrdnPsvl51ooDHbkB:b-nzfm79) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/d889572318826df14a966d4687531395975147c7/cmd/authorizer/Makefile#L51)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

maybe have authorizer_no_cgo depend on test?
</blockquote></details>

Hm, I'd actually wanted not to build a broken container.  So, at least for now, this is as intended.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35)*

**Comment by filmil** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/authorizer/Makefile, line 51 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35#-Kuvk8fFe-T4-dyAYTAT:-KuvrsZWpUiZFYBqmGYA:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/d889572318826df14a966d4687531395975147c7/cmd/authorizer/Makefile#L51)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Hm, I'd actually wanted not to build a broken container.  So, at least for now, this is as intended.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35)*

**Comment by briantkennedy** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35#-:-KuvtEepgw5sWexR3_Fm:bnfp4nl)*

**Comment by filmil** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/authorizer/Makefile, line 51 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35#-Kuvk8fFe-T4-dyAYTAT:-KuzNwrVnkmIU8XxiBCP:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/d889572318826df14a966d4687531395975147c7/cmd/authorizer/Makefile#L51)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/35)*

**Pull request merged**
