### PR TITLE
Add policy node watcher object to handle maintaining connection.

### PR DESCRIPTION
**Pull request by briantkennedy**
* Add unit test example for testing K8S APIs watches.

---
This change is [Reviewable](https://reviewable.io/reviews/mdruskin/kubernetes-enterprise-control/26)

### CODE REVIEW

**Comment by briantkennedy** [comment]
ping

**Comment by filmil** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 35 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWA6wnhEGapauxdwLI:-KuWA6wnhEGapauxdwLJ:b2dd9um) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L35)):*
> ```Go
> 
> type callbackEventHandler struct {
> 	eventCb func(EventType, *policyhierarchy_v1.PolicyNode)
> ```

What is the advantage of doing this, versus defining as an interface.  Do you expect a lot of custom handlers that compose like this?

---

*[pkg/client/policynodewatcher/eventhandler.go, line 39 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWBYM_0c28INzLy9CG:-KuWBYM_0c28INzLy9CH:b-zar0w6) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L39)):*
> ```Go
> }
> 
> // NewEventHandler constructs an event handler from the provided callbacks.
> ```

How about also document what is expected of the callbacks?

One approach would be to define the types for the callbacks, and document those.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 51 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWBNtTujm85JLiAtOI:-KuWBNtTujm85JLiAtOJ:bgpr71a) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L51)):*
> ```Go
> var _ EventHandler = &callbackEventHandler{}
> 
> // PolicyNodeWatcherEvent implements EventHandler
> ```

This type does not seem to appear in code here. What gives?

---

*[pkg/client/policynodewatcher/eventhandler.go, line 56 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWBTnn2CfoLi9z9Sz8:-KuWBTnn2CfoLi9z9Sz9:b-f3hr9a) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L56)):*
> ```Go
> }
> 
> // PolicyNodeWatcherError implements EventHandler
> ```

This type doesn't either.

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 37 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWC4XXWXoirNeptC5Y:-KuWC4XXWXoirNeptC5Z:bdfge4q) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L37)):*
> ```Go
> type EventType string
> 
> // Definitions for EventType constants
> ```

I am not sure that this comment actually helps.  Remove?

If you want to comment something, maybe comment on the constants themselves:

```
const (
        // Added is set for watch events that involve adding an object...
	Added    EventType = "ADDED"
        // this too
	Modified EventType = "MODIFIED"
        // this too
	Deleted  EventType = "DELETED"
)
```

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 60 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWCnFCfMUPgkG66Iao:-KuWCnFCfMUPgkG66Iap:b-kdh9qk) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L60)):*
> ```Go
> // Interface defines the interface for the PolicyNodeWatcher.
> type Interface interface {
> 	// Run starts the watcher, no callbacks will be invoked before Run is called.
> ```

What are the callbacks mentioned here?

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 63 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWCuFRgCHPUu-GOmW-:-KuWCuFRgCHPUu-GOmW0:bjrlxvx) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L63)):*
> ```Go
> 	Run()
> 
> 	// ResourceVersion returns the latest resource version encountered by the watcher.
> ```

Maybe then call it `LastResourceVersion()`?

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 66 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWCxuGeHLZ8iC_P3wm:-KuWCxuGeHLZ8iC_P3wn:b-iexory) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L66)):*
> ```Go
> 	ResourceVersion() string
> 
> 	// Stop instructs the watcher to stop.  This will tear down the watch, however, a callback may be
> ```

Again, this is some implementation detail that leaks: what are callbacks?

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 191 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDP_dZbr2NibMPP4q:-KuWDP_dZbr2NibMPP4r:b-fjq1mu) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L191)):*
> ```Go
> 	prevResourceVersion := w.resourceVersion
> 	w.resourceVersion = resourceVersion
> 	w.resourceVersionMutex.Unlock()
> ```

Also here use the same pattern of deferring unlock?

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 39 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDZQpLq-YtWoraJjm:-KuWDZQpLq-YtWoraJjn:btarak9) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L39)):*
> ```Go
> }
> 
> type PolicyNodeWatcherTestHelper struct {
> ```

Do you expect this type to be exported?  If not, maybe `policyNodeWatcher...` This at least suggests that I don't need to look for it elsewhere.

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 53 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDrEimIlFzeCR5SMC:-KuWDrEimIlFzeCR5SMD:bnl5d4y) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L53)):*
> ```Go
> 	testOperationQueue []*watch.Event
> 
> 	StopCheck func()
> ```

Is this nullable?  Maybe you want to say if it is.

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 79 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWE2ieuxwLWmSNtm-Q:-KuWE2ieuxwLWmSNtm-R:b-enmroz) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L79)):*
> ```Go
> }
> 
> func (h *PolicyNodeWatcherTestHelper) React(action api_testing.Action) (handled bool, ret watch.Interface, err error) {
> ```

Document return values?

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 113 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWECa4JFaNmTaEeGaf:-KuWECa5-TOF7KGQM4Pu:b-b864ss) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L113)):*
> ```Go
> 
> func (h *PolicyNodeWatcherTestHelper) NextResourceVersion() string {
> 	h.resourceVersion += rand.Int() % 5
> ```

What's the magic number 5?

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 137 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWEMBk1V76PCJKprZn:-KuWEMBk1V76PCJKprZo:b4zuckf) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L137)):*
> ```Go
> }
> 
> func (h *PolicyNodeWatcherTestHelper) ActionClose() {
> ```

I think it would be nice to explain how all of these methods are supposed to be used --- it would reduce the amount of figuring out how things fit together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26)*

**Comment by briantkennedy** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 35 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWA6wnhEGapauxdwLI:-KuWHdCVzSva-ggITOPC:braxlgv) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L35)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

What is the advantage of doing this, versus defining as an interface.  Do you expect a lot of custom handlers that compose like this?
</blockquote></details>

It's so people don't have to expose a public OnError/OnEvent inside their own struct and can wire in arbitrary function names to avoid interface naming collisions.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 39 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWBYM_0c28INzLy9CG:-KuWHzQXGRpJRTX_yKOq:b-hgspbo) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L39)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

How about also document what is expected of the callbacks?

One approach would be to define the types for the callbacks, and document those.
</blockquote></details>

One would expect them to work as documented in the EventHandler interface.  It's documented for OnError / OnEvent, I can make that more explicit.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 51 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWBNtTujm85JLiAtOI:-KuWIFbqJgYLK34M7HIR:bsaxqua) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L51)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

This type does not seem to appear in code here. What gives?
</blockquote></details>

Between last night and the time you looked at this I did more work and decided it was related to this enough that it should also go into this commit.  I happened to forget to update a comment while doing so.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 56 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWBTnn2CfoLi9z9Sz8:-KuWI_TB0htcOBpVsttz:bu6xv6u) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L56)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

This type doesn't either.
</blockquote></details>

See previous comment.

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 37 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWC4XXWXoirNeptC5Y:-KuWJERuO2u40CheOJ1x:b-h2xdwh) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L37)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

I am not sure that this comment actually helps.  Remove?

If you want to comment something, maybe comment on the constants themselves:

```
const (
        // Added is set for watch events that involve adding an object...
	Added    EventType = "ADDED"
        // this too
	Modified EventType = "MODIFIED"
        // this too
	Deleted  EventType = "DELETED"
)
```
</blockquote></details>

I was hoping that the names of the events themselves would be straightforward enough to let people know what they meant given that I'm going to be defining them in terms of their own name.

Does it really need:
//  X is the event you will get when something is x-ed

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 60 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWCnFCfMUPgkG66Iao:-KuWK0dIDo4W7xPUDmru:b-j3gfkl) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L60)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

What are the callbacks mentioned here?
</blockquote></details>

I've moved providing the EventHandler from the constructor to the Run method.

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 63 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWCuFRgCHPUu-GOmW-:-KuWKt4FOP9tL_lNxh6J:bq5wuc9) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L63)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Maybe then call it `LastResourceVersion()`?
</blockquote></details>

Updated comment.

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 66 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWCxuGeHLZ8iC_P3wm:-KuWLWruNU9gycEz9Ttg:b-7ql1td) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L66)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Again, this is some implementation detail that leaks: what are callbacks?
</blockquote></details>

fixed

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 191 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDP_dZbr2NibMPP4q:-KuWMmximv6TXUbjgwLG:b-xchy85) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L191)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Also here use the same pattern of deferring unlock?
</blockquote></details>

That's going to put glog inside the lock which seems like a bad idea.

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 39 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDZQpLq-YtWoraJjm:-KuWMz8GS8SxW6gEgffM:bcy3ulw) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L39)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Do you expect this type to be exported?  If not, maybe `policyNodeWatcher...` This at least suggests that I don't need to look for it elsewhere.
</blockquote></details>

no, this is a testcase, I don't plan on this being exported.  I've added a class level doc to explain what's going on, and I'll comment more about the data structure fields, but I'm not going to put a ton of work into making this re-usable since nobody should be using this since it's specific to testing the PolicyNodeWatcher

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 53 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDrEimIlFzeCR5SMC:-KuWN1P4g07JC5HTX7Ql:bh8g4hz) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L53)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Is this nullable?  Maybe you want to say if it is.
</blockquote></details>

testcase

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 79 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWE2ieuxwLWmSNtm-Q:-KuWN2a0Ji3RX3FjIEMl:bh8g4hz) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L79)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Document return values?
</blockquote></details>

testcase

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 113 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWECa4JFaNmTaEeGaf:-KuWN2zF814eH9S9BOYk:b-xhzufd) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L113)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

What's the magic number 5?
</blockquote></details>

we don't expect resourceVersion to be sequential

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 137 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWEMBk1V76PCJKprZn:-KuWN3xRVzrd3V6S1byx:b-xz0kah) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L137)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

I think it would be nice to explain how all of these methods are supposed to be used --- it would reduce the amount of figuring out how things fit together.
</blockquote></details>

testcase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26)*

**Comment by filmil** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 39 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWBYM_0c28INzLy9CG:-KuWRe5uLxwd72kdxEpr:b-cg14tf) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/eventhandler.go#L39)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

One would expect them to work as documented in the EventHandler interface.  It's documented for OnError / OnEvent, I can make that more explicit.
</blockquote></details>

That would work.  Leaving to you to decide.

---

*[pkg/client/policynodewatcher/eventhandler.go, line 22 at r2](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWPywQZd45pj_O8hze:-KuWPywQZd45pj_O8hzf:b-ieq89u) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/e755ca71104ab65200720af2521bc0491dd6f20c/pkg/client/policynodewatcher/eventhandler.go#L22)):*
> ```Go
> 
> // EventHandler is an interface for handling events from the PolicyNodeWatcher.  Note that events
> // will be called from a gothread, but all callbacks are guaranteed to be serialized
> ```

nit: gothread -> goroutine?

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 37 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWC4XXWXoirNeptC5Y:-KuWPJbEVi86R8kAebe_:b-lghrqq) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L37)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

I was hoping that the names of the events themselves would be straightforward enough to let people know what they meant given that I'm going to be defining them in terms of their own name.

Does it really need:
//  X is the event you will get when something is x-ed
</blockquote></details>

OK

If you think there's nothing to be said about the constants then remove this comment as well. I don't think it gives us any extra info beyond what's already in the `const( )` section.

---

*[pkg/client/policynodewatcher/policynodewatcher.go, line 191 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDP_dZbr2NibMPP4q:-KuWPavzQlDLvO4-wszW:bp7yvpc) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher.go#L191)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

That's going to put glog inside the lock which seems like a bad idea.
</blockquote></details>

OK

Good point.

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 39 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDZQpLq-YtWoraJjm:-KuWRuQIYluvGnWR8rBF:bb70uqp) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L39)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

no, this is a testcase, I don't plan on this being exported.  I've added a class level doc to explain what's going on, and I'll comment more about the data structure fields, but I'm not going to put a ton of work into making this re-usable since nobody should be using this since it's specific to testing the PolicyNodeWatcher
</blockquote></details>

OK

---

*[pkg/client/policynodewatcher/policynodewatcher_test.go, line 53 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-KuWDrEimIlFzeCR5SMC:-KuWQeucAJcOQSvlk7wF:b-fci13y) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/9681cc20ae4df104531dac8c18bb1a34987af9ec/pkg/client/policynodewatcher/policynodewatcher_test.go#L53)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

testcase
</blockquote></details>


OK

Hm, I guess that if it can be nullable then one can assume that it is. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/26#-:-KuWSmYDz08J-4T050Oj:bnfp4nl)*

**Pull request merged**
