### PR TITLE
Move syncer operations out of client and into separate package.

### PR DESCRIPTION
**Pull request by briantkennedy**
Slight refactor for code that was in pkg/client and relocate to
pkg/syncer.  Thorough unit tests are a TODO at the moment since we will
likely need to add in funcionality for unpacking resources in the near
future.

Also some scripts for manually running syncer pipeline.

---
This change is [Reviewable](https://reviewable.io/reviews/mdruskin/kubernetes-enterprise-control/34)

### CODE REVIEW

**Comment by briantkennedy** [comment]
bump

**Comment by briantkennedy** [comment]
FYI: I'm submitting this at 5pm if there's no comments.

**Comment by filmil** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/34#-:-Kv-LOiTfPjfX8UMrckf:bnfp4nl)*

**Comment by filmil** [comment]
LGTM

Sorry, I thought that I had LGTM'd this change earlier. Apparently not.  

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/34#-:-Kv-LU0eDLDitBQ-7Vck:b-57k033)*

**Pull request merged**
