### PR TITLE
Add watching demo code.

### PR DESCRIPTION
**Pull request by briantkennedy**
This change is [Reviewable](https://reviewable.io/reviews/mdruskin/kubernetes-enterprise-control/14)

### CODE REVIEW

**Comment by filmil** [comment]
Care to describe in brief in the commit description what the demo does?

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/listnamespaces/listnamespaces.go, line 95 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6Ag0cwJeJiaA-1yY9:-Ku6Ag0cwJeJiaA-1yYA:b-the5yy) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L95)):*
> ```Go
> }
> 
> // Demonstrate namespace sync by syncing list of NS (create), then part of list (update)
> ```

nit: go-canonical comments are:

syncNamespacesDemo demonstrates namespace sync... (I think that refactoring tools also support it automatically.)

---

*[cmd/listnamespaces/listnamespaces.go, line 130 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6AI-hkTzProK6QPu-:-Ku6AI-hkTzProK6QPu0:b-45j66m) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L130)):*
> ```Go
> }
> 
> func WatchSyncPolicyHierarchy(clusterClient *client.Client) {
> ```

Care to document public API? It would be nice to add that, so that we know what we *want* this function to do.  We can then easily check if it really does what it says on the label.  Without that, any behavior becomes specification in effect.

---

*[cmd/listnamespaces/listnamespaces.go, line 154 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku5sLrT0Agx7VNFj_6V:-Ku5sLrT0Agx7VNFj_6W:bcnbkcc) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L154)):*
> closed
I think it's more customary to do s/closed/ok/, because otherwise the following condition reads: "if not closed, then say channel closed".

---

*[cmd/listnamespaces/listnamespaces.go, line 169 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku5siThjgP6Y81-t8Og:-Ku5siThjgP6Y81-t8Oh:bkhfou2) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L169)):*
> ```Go
> 	// wait for signal
> 	c := make(chan os.Signal, 1)
> 	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
> ```

Not sure what this is achieving?  It's installing a signal handler, but then invoking it immediately. What gives?

---

*[pkg/client/client.go, line 156 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6AwXxYCdLLFz_tZzb:-Ku6AwXxYCdLLFz_tZzc:b46wxej) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/pkg/client/client.go#L156)):*
> ```Go
> }
> 
> func ExtractNamespaces(policyNodes []policyhierarchy_v1.PolicyNode) []string {
> ```

Explain what the function does?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-:-Ku5rfLpyUt4T6eYzgHY:b-iqudpy)*

**Comment by briantkennedy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/listnamespaces/listnamespaces.go, line 95 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6Ag0cwJeJiaA-1yY9:-Ku6CC8Wf71ZBWnr0LHt:b-s1hqat) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L95)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

nit: go-canonical comments are:

syncNamespacesDemo demonstrates namespace sync... (I think that refactoring tools also support it automatically.)
</blockquote></details>

This isn't a public function, does not require the // [functionname] documentation.

---

*[cmd/listnamespaces/listnamespaces.go, line 130 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6AI-hkTzProK6QPu-:-Ku6CQT4QVXBoDX8J0a9:bh2xbkf) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L130)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Care to document public API? It would be nice to add that, so that we know what we *want* this function to do.  We can then easily check if it really does what it says on the label.  Without that, any behavior becomes specification in effect.
</blockquote></details>

This technically isn't usable by any other code since it's in package main.  I'll add the doc.

---

*[cmd/listnamespaces/listnamespaces.go, line 154 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku5sLrT0Agx7VNFj_6V:-Ku6CsCwYZ_hR_KBycdk:bb7f2mf) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L154)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

> closed
I think it's more customary to do s/closed/ok/, because otherwise the following condition reads: "if not closed, then say channel closed".
</blockquote></details>

done

---

*[cmd/listnamespaces/listnamespaces.go, line 169 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku5siThjgP6Y81-t8Og:-Ku6CtIU9z294LAvpr6o:b-ljwj4h) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L169)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Not sure what this is achieving?  It's installing a signal handler, but then invoking it immediately. What gives?
</blockquote></details>

That's not how signal works

---

*[pkg/client/client.go, line 156 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6AwXxYCdLLFz_tZzb:-Ku6DErdnMuxPiy4glYa:bb7f2mf) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/pkg/client/client.go#L156)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Explain what the function does?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14)*

**Comment by filmil** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/listnamespaces/listnamespaces.go, line 130 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6AI-hkTzProK6QPu-:-Ku6F3Ubr0I1NA91qnCT:bkjxtdu) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L130)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

This technically isn't usable by any other code since it's in package main.  I'll add the doc.
</blockquote></details>

True; that said it's a lot of code and it would be nice to have a black-box summary of what it is intended to do. 

---

*[cmd/listnamespaces/listnamespaces.go, line 169 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku5siThjgP6Y81-t8Og:-Ku6EvhQalMBj6bm38PL:b96qh9n) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L169)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

That's not how signal works
</blockquote></details>

LGTM

Whoops, sorry -- I keep forgetting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-:-Ku6FEp7jSlilxW3cg4x:bnfp4nl)*

**Comment by filmil** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/listnamespaces/listnamespaces.go, line 95 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14#-Ku6Ag0cwJeJiaA-1yY9:-Ku6FjbK-GEC9-bq09Bj:bb6ywmx) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/b0728173f8c7aa978abd8e3cb6763721e61b7565/cmd/listnamespaces/listnamespaces.go#L95)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

This isn't a public function, does not require the // [functionname] documentation.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14)*

**Comment by filmil** [comment]
Reviewed 1 of 2 files at r1.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/14)*

**Pull request merged**
