### PR TITLE
Webhook AdmissionController - Simple Resource Quota Controller

### PR DESCRIPTION
**Pull request by mdruskin**
This change is [Reviewable](https://reviewable.io/reviews/mdruskin/kubernetes-enterprise-control/45)

### CODE REVIEW

**Comment by briantkennedy** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/admission-controller/resource-quota/gencert.sh, line 11 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvA3EMTL7RkhZLck_yC:-KvA3EMTL7RkhZLck_yD:b8o8ngr) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/gencert.sh#L11)):*
> ```Shell
> 
> cat > server.conf << EOF
> [req]
> ```

if you're not doing variable substitution here, probably better to just check in the file itself

---

*[deploy/admission-controller/resource-quota/register.sh, line 16 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvA1LFqJ4lFI7jaXEXP:-KvA1LFqJ4lFI7jaXEXQ:b-70utza) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/register.sh#L16)):*
> ```Shell
>     rules:
>       - operations:
>           - CREATE
> ```

is there also a modify?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45)*

**Comment by briantkennedy** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-:-KvA41uXOqgfL-bDSaPB:bnfp4nl)*

**Comment by filmil** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/admission-controller/resource-quota/main.go, line 113 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDbEkOf1tLEDqze8uW:-KvDbEkOf1tLEDqze8uX:braotfv) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/cmd/admission-controller/resource-quota/main.go#L113)):*
> ```Go
> // Server configures and runs a TLS-enabled server from passed-in flags using
> // the supplied handler.
> func Server(handler handlerFunc) *http.Server {
> ```

Note here, there's a bit of code that repeats from `cmd/authorizer/main.go`.

Think about whether you want to extract common code to a separate package.  Since we have 2 instances of it, maybe it doesn't pay off.  A third one would probably pay for a refactor.

Leaving to you to decide.

---

*[deploy/admission-controller/resource-quota/Dockerfile, line 19 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDfCdW2HlqESvFUgwI:-KvDfCdW2HlqESvFUgwJ:b-qubqfp) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/Dockerfile#L19)):*
> ```Dockerfile
> ADD server.key server.key
> ADD server.crt server.crt
> EXPOSE 8000
> ```

Hm, we may want to standardize on this port choice at some point.

---

*[deploy/admission-controller/resource-quota/gencert.sh, line 7 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDfIfoPKAeRw95evHh:-KvDfIfoPKAeRw95evHi:b-gtatqw) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/gencert.sh#L7)):*
> ```Shell
> # to be called by the api server.
> 
> # The name of the service (and the namespace it runs in).
> ```

Maybe note that this CN is mandated by Kubernetes.

---

*[deploy/admission-controller/resource-quota/gencert.sh, line 11 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvA3EMTL7RkhZLck_yC:-KvDbi2I_m8GxMqs0T1G:bx1uz2f) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/gencert.sh#L11)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

if you're not doing variable substitution here, probably better to just check in the file itself
</blockquote></details>

CN_BASE could be moved into this config file if desired, for example.  Then it'd make more sense.

---

*[deploy/admission-controller/resource-quota/pod-template.yaml, line 1 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDfY_c_gO5_3Z-48IO:-KvDfY_c_gO5_3Z-48IP:bb6pocg) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/pod-template.yaml#L1)):*
> ```YAML
> apiVersion: v1
> ```

nit: maybe change the extension of the template from yaml to something else (`.m4`?) to indicate that without substitution the template is not useful.

---

*[pkg/admission-controller/admission_controller.go, line 23 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDcf8A75TLmeYQdlYa:-KvDcf8A75TLmeYQdlYb:b-pehud9) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/admission_controller.go#L23)):*
> ```Go
> )
> 
> type Controller interface {
> ```

Care to document how this interface is to be used, and its methods?  It certainly looks important, so I think it deserves an explanation.

nit: go conventions seem to favor that an interface with only one method, say`X`, has the name `Xer`.  So maybe `Admitter`.
This somewhat reduces the cognitive load to remember the method names.

---

*[pkg/admission-controller/resource_quota.go, line 28 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDdgY0XHkSGIgPWvSW:-KvDdgY0XHkSGIgPWvSX:b-pd2d3j) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/resource_quota.go#L28)):*
> ```Go
> )
> 
> type ResourceQuotaController struct {
> ```

nit: you may want to add:

```
var _ Controller = (*ResourceQuotaController)(nil)
```

This will ensure that `ResourceQuotaController` always implements the interface `Controller`, but more importantly, will tell the readers of this code what interface is supposed to be implemented.  It helps, RLY.

---

*[pkg/admission-controller/resource_quota.go, line 34 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDeF5_KE_35p6isypu:-KvDeF5_KE_35p6isypv:bj4ulmj) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/resource_quota.go#L34)):*
> ```Go
> // Decides whether to admit a request
> func (r* ResourceQuotaController) Admit(review admissionv1alpha1.AdmissionReview) *admissionv1alpha1.AdmissionReviewStatus {
> 	reviewStatus := admissionv1alpha1.AdmissionReviewStatus{}
> ```

nit: You can initialize the thing in place

```
admissionv1alpha.AdmissionReviewStatus{
  Allowed: true,
  Status: &metav1.Status{
    Reason: "ADMITTED, yay!",
  },
}
```

---

*[pkg/admission-controller/resource_quota.go, line 46 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDeX7zR20_0WPUejHf:-KvDeX7zR20_0WPUejHg:b-9pnlxq) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/resource_quota.go#L46)):*
> ```Go
> }
> 
> // Blocks creation of secrets
> ```

nit: this comment doesn't offer additional info over what the function name says.  More useful would be to write it as a mini-spec of what we expect the result to be.

For example:

```
// blockSecrets forbids the creation of resources with the special name 'secrets'.  It is used
// to test admission control DENY decisions.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45)*

**Comment by mdruskin** [comment]
Review status: 6 of 13 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[deploy/admission-controller/resource-quota/gencert.sh, line 7 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDfIfoPKAeRw95evHh:-KvE5g78GxxwuiwocW3w:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/gencert.sh#L7)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Maybe note that this CN is mandated by Kubernetes.
</blockquote></details>

Done.

---

*[deploy/admission-controller/resource-quota/gencert.sh, line 11 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvA3EMTL7RkhZLck_yC:-KvE5ivNs5q2GLUwPEeX:b63v30b) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/gencert.sh#L11)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

CN_BASE could be moved into this config file if desired, for example.  Then it'd make more sense.
</blockquote></details>

I've created a separate file, since CN should be in the subject as far as I understand.

---

*[deploy/admission-controller/resource-quota/pod-template.yaml, line 1 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDfY_c_gO5_3Z-48IO:-KvE6CtFYJXeSYWbWMQz:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/pod-template.yaml#L1)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

nit: maybe change the extension of the template from yaml to something else (`.m4`?) to indicate that without substitution the template is not useful.
</blockquote></details>

Done.

---

*[deploy/admission-controller/resource-quota/register.sh, line 16 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvA1LFqJ4lFI7jaXEXP:-KvA4xDQgX_ykTcUPRSE:bad8pj7) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/deploy/admission-controller/resource-quota/register.sh#L16)):*
<details><summary><i>Previously, briantkennedy (Brian Kennedy) wrote…</i></summary><blockquote>

is there also a modify?
</blockquote></details>

Yes, I can make it ALL also, this was just an example for now...

---

*[pkg/admission-controller/admission_controller.go, line 23 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDcf8A75TLmeYQdlYa:-KvE6KR6H3CcCdl0zGKO:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/admission_controller.go#L23)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Care to document how this interface is to be used, and its methods?  It certainly looks important, so I think it deserves an explanation.

nit: go conventions seem to favor that an interface with only one method, say`X`, has the name `Xer`.  So maybe `Admitter`.
This somewhat reduces the cognitive load to remember the method names.
</blockquote></details>

Done.

---

*[pkg/admission-controller/resource_quota.go, line 28 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDdgY0XHkSGIgPWvSW:-KvE6hwd2LyI2NITBlyx:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/resource_quota.go#L28)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

nit: you may want to add:

```
var _ Controller = (*ResourceQuotaController)(nil)
```

This will ensure that `ResourceQuotaController` always implements the interface `Controller`, but more importantly, will tell the readers of this code what interface is supposed to be implemented.  It helps, RLY.
</blockquote></details>

Done.

---

*[pkg/admission-controller/resource_quota.go, line 34 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDeF5_KE_35p6isypu:-KvE7bBbi_Khl2i5q-8M:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/resource_quota.go#L34)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

nit: You can initialize the thing in place

```
admissionv1alpha.AdmissionReviewStatus{
  Allowed: true,
  Status: &metav1.Status{
    Reason: "ADMITTED, yay!",
  },
}
```

</blockquote></details>

Done.

---

*[pkg/admission-controller/resource_quota.go, line 46 at r1](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45#-KvDeX7zR20_0WPUejHf:-KvE7nXXsOlHqXs-a561:b-896fix) ([raw file](https://github.com/mdruskin/kubernetes-enterprise-control/blob/459e54fbc06021bd24f1d636bd4161b9e6624877/pkg/admission-controller/resource_quota.go#L46)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

nit: this comment doesn't offer additional info over what the function name says.  More useful would be to write it as a mini-spec of what we expect the result to be.

For example:

```
// blockSecrets forbids the creation of resources with the special name 'secrets'.  It is used
// to test admission control DENY decisions.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mdruskin/kubernetes-enterprise-control/45)*

**Pull request merged**
